[project]
name = "backend"
version = "0.1.0"
description = "API-only Django backend scaffold"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Eram Dev Team", email = "eramdevteam@gmail.com" },
]
requires-python = "==3.14.*"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "argon2-cffi==25.1.0",
  "django==6.0.7",
  "django-allauth[mfa]==65.18.0",
  "django-anymail[amazon-ses]==15.0",
  "django-cors-headers==4.9.0",
  "django-ninja==1.6.2",
  "django-storages[s3]==1.14.6",
  "gunicorn==26.0.0",
  "psycopg[binary]==3.3.4",
  "sentry-sdk==2.64.0",
]

[dependency-groups]
dev = [
  "coverage==7.15.0",
  "django-debug-toolbar==7.0.0",
  "django-extensions>=4.1",
  "django-stubs[compatible-mypy]==6.0.6",
  "django-upgrade==1.31.1",
  "factory-boy==3.3.3",
  "ipdb>=0.13.13",
  "mypy==2.1.0",
  "pre-commit==4.6.0",
  "psycopg[binary]==3.3.4",
  "pytest==9.1.1",
  "pytest-django==4.12.0",
  "pytest-sugar>=1.1.1",
  "ruff==0.15.21",
  "werkzeug[watchdog]>=3.1.8",
]

# ==== ruff ====
[tool.ruff]
# Exclude a variety of commonly ignored directories.
extend-exclude = [
  "*/migrations/*.py",
  "staticfiles/*",
]
lint.select = [
  "A",
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "C90",
  "COM",
  "DJ",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  "FA",
  "FBT",
  "FLY",
  "G",
  "I",
  "ICN",
  "INP",
  "INT",
  "ISC",
  "N",
  "PD",
  "PERF",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "SLF",
  "SLOT",
  "T10",
  "T20",
  "TC",
  "TID",
  "TRY",
  "UP",
  "W",
  "YTT",
]
lint.ignore = [
  "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
  "S101",   # Use of assert detected https://docs.astral.sh/ruff/rules/assert/
  "SIM102", # sometimes it's better to nest
  # of types for comparison.
  # Deactivated because it can make the code slow:
  # https://github.com/astral-sh/ruff/issues/7871
]
lint.isort.force-single-line = true

# ==== mypy ====
[tool.mypy]
ignore_missing_imports = true
python_version = "3.14"
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
plugins = [
  "mypy_django_plugin.main",
]
warn_unused_configs = true
overrides = [
  # Django migrations should not produce any errors:
  { module = "*.migrations.*", ignore_errors = true },
]

[tool.django-stubs]
django_settings_module = "config.settings.test"

# ==== pytest ====
[tool.pytest]
addopts = [
  "--ds=config.settings.test",
  "--reuse-db",
  "--import-mode=importlib",
]
minversion = "9.0"
python_files = [
  "tests.py",
  "test_*.py",
]

[tool.coverage]
# ==== Coverage ====
run.include = [ "apps/**", "config/**" ]
run.omit = [ "*/migrations/*", "*/tests/*" ]
