# Generated by Django 6.1 on 2026-08-29 11:30

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('gateway', models.CharField(choices=[('tap', 'Tap'), ('paymob', 'Paymob')], max_length=10, verbose_name='gateway')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('gateway_customer_id', models.CharField(blank=True, max_length=255, verbose_name='gateway customer id')),
                ('gateway_agreement_id', models.CharField(blank=True, max_length=255, verbose_name='gateway agreement id')),
                ('fingerprint', models.CharField(blank=True, max_length=128, verbose_name='fingerprint')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='brand')),
                ('last4', models.CharField(blank=True, max_length=4, verbose_name='last four digits')),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='expiry month')),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='expiry year')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_cards', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saved card',
                'verbose_name_plural': 'saved cards',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(choices=[('wallet_topup', 'Wallet top-up'), ('other', 'Other')], max_length=20, verbose_name='kind')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('currency', models.CharField(choices=[('SAR', 'Saudi riyal'), ('EGP', 'Egyptian pound')], max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunding', 'Refund pending'), ('refunded', 'Refunded')], default='pending', max_length=10, verbose_name='status')),
                ('gateway', models.CharField(choices=[('tap', 'Tap'), ('paymob', 'Paymob')], max_length=10, verbose_name='gateway')),
                ('save_card_requested', models.BooleanField(default=False, verbose_name='save card requested')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='idempotency key')),
                ('gateway_charge_id', models.CharField(blank=True, max_length=255, verbose_name='gateway charge id')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='gateway transaction id')),
                ('checkout_url', models.URLField(blank=True, max_length=500, verbose_name='checkout URL')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='gateway response')),
                ('gateway_callback', models.JSONField(blank=True, null=True, verbose_name='gateway callback')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('refund_attempted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='refund attempted at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('saved_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.savedcard', verbose_name='saved card')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='balance')),
                ('currency', models.CharField(choices=[('SAR', 'Saudi riyal'), ('EGP', 'Egyptian pound')], max_length=3, verbose_name='currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(choices=[('topup', 'Top-up'), ('refund', 'Refund'), ('adjustment', 'Manual adjustment'), ('payment', 'Payment')], max_length=20, verbose_name='kind')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance after')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='payments.payment', verbose_name='payment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'wallet transaction',
                'verbose_name_plural': 'wallet transactions',
            },
        ),
        migrations.AddIndex(
            model_name='savedcard',
            index=models.Index(fields=['user', 'gateway'], name='payments_sa_user_id_115ea9_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedcard',
            constraint=models.UniqueConstraint(fields=('gateway', 'token'), name='savedcard_gateway_token_unique'),
        ),
        migrations.AddConstraint(
            model_name='savedcard',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint', ''), _negated=True), fields=('user', 'gateway', 'fingerprint'), name='savedcard_user_gateway_fingerprint_unique'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_charge_id'], name='payments_pa_gateway_334498_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
    ]
