# Generated by Django 6.1 on 2026-09-04 22:55

import django.db.models.functions.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.UUIDField(
                db_default=django.db.models.functions.uuid.UUID7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="idempotency_key",
            field=models.UUIDField(
                db_default=django.db.models.functions.uuid.UUID7(),
                editable=False,
                unique=True,
                verbose_name="idempotency key",
            ),
        ),
        migrations.AlterField(
            model_name="savedcard",
            name="id",
            field=models.UUIDField(
                db_default=django.db.models.functions.uuid.UUID7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="id",
            field=models.UUIDField(
                db_default=django.db.models.functions.uuid.UUID7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="id",
            field=models.UUIDField(
                db_default=django.db.models.functions.uuid.UUID7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "updated_at"], name="payments_pa_status_d4d624_idx"
            ),
        ),
    ]
