# Generated by Django 6.1 on 2026-09-05 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_idempotency_key_db_default_status_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="client_request_id",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="client request id"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_refund_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                verbose_name="gateway refund id",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_refund_response",
            field=models.JSONField(
                blank=True, null=True, verbose_name="gateway refund response"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id__isnull", False)),
                fields=("user", "client_request_id"),
                name="payment_client_request_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_transaction_id", ""), _negated=True),
                fields=("gateway", "gateway_transaction_id"),
                name="payment_provider_transaction_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "topup")),
                fields=("payment",),
                name="wallet_topup_payment_unique",
            ),
        ),
    ]
