# Generated by Django 6.0.7 on 2026-07-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_backfill_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_attempted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='refund attempted at'),
        ),
    ]
