# Generated by Django 6.0.7 on 2026-07-18 16:27

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_refund_attempted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='save_card_requested',
            field=models.BooleanField(default=False, verbose_name='save card requested'),
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('gateway', models.CharField(choices=[('tap', 'Tap'), ('paymob', 'Paymob'), ('fake', 'Fake (local)')], max_length=10, verbose_name='gateway')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('gateway_customer_id', models.CharField(blank=True, max_length=255, verbose_name='gateway customer id')),
                ('gateway_agreement_id', models.CharField(blank=True, max_length=255, verbose_name='gateway agreement id')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='brand')),
                ('last4', models.CharField(blank=True, max_length=4, verbose_name='last four digits')),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='expiry month')),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='expiry year')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_cards', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saved card',
                'verbose_name_plural': 'saved cards',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='saved_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.savedcard', verbose_name='saved card'),
        ),
        migrations.AddIndex(
            model_name='savedcard',
            index=models.Index(fields=['user', 'gateway'], name='payments_sa_user_id_115ea9_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedcard',
            constraint=models.UniqueConstraint(fields=('gateway', 'token'), name='savedcard_gateway_token_unique'),
        ),
    ]
