# Generated by Django 6.0.7 on 2026-07-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_save_card_requested_savedcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('wallet_topup', 'Wallet top-up'), ('card_verification', 'Card verification'), ('other', 'Other')], max_length=20, verbose_name='kind'),
        ),
    ]
