# Generated by Django 6.1 on 2026-08-24 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcard',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=128, verbose_name='fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='savedcard',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint', ''), _negated=True), fields=('user', 'gateway', 'fingerprint'), name='savedcard_user_gateway_fingerprint_unique'),
        ),
    ]
