# Generated by Django 6.1 on 2026-08-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_savedcard_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('tap', 'Tap'), ('paymob', 'Paymob')], max_length=10, verbose_name='gateway'),
        ),
        migrations.AlterField(
            model_name='savedcard',
            name='gateway',
            field=models.CharField(choices=[('tap', 'Tap'), ('paymob', 'Paymob')], max_length=10, verbose_name='gateway'),
        ),
    ]
