# Generated by Django 6.1 on 2026-08-29 20:39

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='code')),
                ('alpha_3', models.CharField(max_length=3, unique=True, verbose_name='alpha-3 code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('dial_code', models.CharField(max_length=5, verbose_name='dial code')),
                ('phone_example', models.CharField(max_length=32, verbose_name='phone example')),
                ('max_phone_length', models.PositiveSmallIntegerField(verbose_name='max phone length')),
                ('currency', models.CharField(db_index=True, max_length=3, verbose_name='currency')),
                ('flag', models.ImageField(blank=True, upload_to='location/flags/', verbose_name='flag')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
    ]
