# Generated by Django 6.1 on 2026-09-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='max_phone_length',
            field=models.PositiveSmallIntegerField(help_text='Longest national number the dial plan allows (digits).', verbose_name='max phone length'),
        ),
    ]
