# Generated by Django 6.1 on 2026-08-29 21:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.datetime
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        # PostGIS must exist before the MultiPolygonField column; idempotent.
        # Needs rds_superuser on RDS - the shared dev database gets it from the
        # runbook (docs/DEPLOYMENT.md), production's master user creates it here.
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('region_code', models.CharField(db_index=True, max_length=20, verbose_name='region code')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='code')),
                ('name', models.TextField(verbose_name='name')),
                ('name_ar', models.TextField(null=True, verbose_name='name')),
                ('name_en', models.TextField(null=True, verbose_name='name')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geometry')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='location.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'zone',
                'verbose_name_plural': 'zones',
                'ordering': ['code'],
            },
        ),
    ]
