# Generated by Django 6.1 on 2026-08-29 11:30

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationKindConfig',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(choices=[('welcome', 'Welcome'), ('announcement', 'Announcement'), ('payment_paid', 'Payment received'), ('wallet_credited', 'Wallet credited')], max_length=50, unique=True, verbose_name='action')),
                ('channels', models.JSONField(default=list, verbose_name='channels')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('body_ar', models.TextField(null=True, verbose_name='body')),
                ('body_en', models.TextField(null=True, verbose_name='body')),
            ],
            options={
                'verbose_name': 'notification action',
                'verbose_name_plural': 'notification actions',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(choices=[('welcome', 'Welcome'), ('announcement', 'Announcement'), ('payment_paid', 'Payment received'), ('wallet_credited', 'Wallet credited')], max_length=50, verbose_name='kind')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='context')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dispatching', 'Dispatching'), ('dispatched', 'Dispatched'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='status')),
                ('language', models.CharField(blank=True, choices=[('ar', 'Arabic'), ('en', 'English')], max_length=2, verbose_name='language filter')),
                ('require_device', models.BooleanField(default=False, help_text='Skip users with no registered device. They would receive an inbox entry but no push.', verbose_name='registered device required')),
                ('joined_after', models.DateField(blank=True, null=True, verbose_name='joined on or after')),
                ('joined_before', models.DateField(blank=True, null=True, verbose_name='joined on or before')),
                ('channels', models.JSONField(blank=True, default=list, verbose_name='channels')),
                ('dispatch_cursor', models.UUIDField(blank=True, null=True, verbose_name='dispatch cursor')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='total recipients')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='total deliveries')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='sent')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='failed')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='skipped')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'broadcast',
                'verbose_name_plural': 'broadcasts',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('registration_id', models.TextField(unique=True, verbose_name='registration id')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10, verbose_name='platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(choices=[('welcome', 'Welcome'), ('announcement', 'Announcement'), ('payment_paid', 'Payment received'), ('wallet_credited', 'Wallet credited')], max_length=50, verbose_name='kind')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='context')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.broadcast', verbose_name='broadcast')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('channel', models.CharField(choices=[('push', 'Push'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='channel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='status')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='provider')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='provider message id')),
                ('detail', models.TextField(blank=True, verbose_name='detail')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.broadcast', verbose_name='broadcast')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'notification delivery',
                'verbose_name_plural': 'notification deliveries',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('broadcast__isnull', False)), fields=('broadcast', 'recipient'), name='uniq_notification_broadcast_recipient'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_edd073_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(condition=models.Q(('broadcast__isnull', False)), fields=['broadcast', 'status'], name='idx_delivery_broadcast_status'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(condition=models.Q(('broadcast__isnull', True), ('status__in', ['pending', 'processing'])), fields=['status', 'created_at'], name='idx_delivery_txn_sweep'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='uniq_delivery_notification_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('provider', 'provider_message_id'), name='uniq_delivery_provider_message_id'),
        ),
    ]
