# Generated by Django 6.0.7 on 2026-07-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='channels',
            field=models.JSONField(blank=True, default=list, verbose_name='channels'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='joined_after',
            field=models.DateField(blank=True, null=True, verbose_name='joined on or after'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='joined_before',
            field=models.DateField(blank=True, null=True, verbose_name='joined on or before'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='require_device',
            field=models.BooleanField(default=False, help_text='Skip users with no registered device. They would receive an inbox entry but no push.', verbose_name='registered device required'),
        ),
    ]
