# Generated by Django 6.1 on 2026-08-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='recipient_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='specific recipients'),
        ),
    ]
