# Generated by Django 6.0.7 on 2026-07-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('announcement', 'Announcement'), ('payment_paid', 'Payment received'), ('wallet_credited', 'Wallet credited')], max_length=50, verbose_name='kind'),
        ),
    ]
