# Generated by Django 6.1 on 2026-09-04 22:55

import apps.notifications.constants
import django.db.models.functions.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_broadcast_recipient_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='id',
            field=models.UUIDField(db_default=django.db.models.functions.uuid.UUID7(), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='kind',
            field=models.CharField(choices=apps.notifications.constants.notification_kind_choices, max_length=50, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(db_default=django.db.models.functions.uuid.UUID7(), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='registration_id',
            field=models.CharField(max_length=512, unique=True, verbose_name='registration id'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(db_default=django.db.models.functions.uuid.UUID7(), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=apps.notifications.constants.notification_kind_choices, max_length=50, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=apps.notifications.constants.channel_choices, max_length=20, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='id',
            field=models.UUIDField(db_default=django.db.models.functions.uuid.UUID7(), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationkindconfig',
            name='id',
            field=models.UUIDField(db_default=django.db.models.functions.uuid.UUID7(), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationkindconfig',
            name='kind',
            field=models.CharField(choices=apps.notifications.constants.notification_kind_choices, max_length=50, unique=True, verbose_name='action'),
        ),
    ]
